- 0.8.8 src

diff --git a/mlt/src/modules/qimage/configure b/mlt/src/modules/qimage/configure
--- a/mlt/src/modules/qimage/configure
+++ b/mlt/src/modules/qimage/configure
@@ -12,6 +12,7 @@ QImage options:
   --kde-includedir        - Location of KDE include directory [/usr/include/kde]
   --exif-libdir           - Location of libexif lib directory [/usr/lib]
   --exif-includedir       - Location of libexif include directory [/usr/include/libexif]
+  --without-kde           - Don't link to KDE libraries
 
 EOF
 
@@ -31,21 +32,8 @@ else
 		;;
 	esac
 
-	qimage_includedir=/usr/include/qt4
-	qimage_libdir=/usr/lib/qt4
-
-	if [ ! -d "$qimage_libdir" -o ! -d "$qimage_includedir" ]
-	then
-		qimage_includedir=/usr/include/qt3
-		qimage_libdir=/usr/lib/qt3
-		kde_includedir=/usr/include/kde
-		kde_libdir=/usr/lib
-		if [ "$KDEDIR" != "" ]
-		then
-			kde_includedir="$KDEDIR/include"
-			kde_libdir="$KDEDIR/lib"
-		fi
-	fi
+	qimage_includedir=
+	qimage_libdir=
 
 	if [ "$QTDIR" != "" ]
 	then
@@ -55,6 +43,7 @@ else
 
 	export force_qt3=
 	export qt4_found=
+	export without_kde=
 
 	for i in "$@"
 	do
@@ -66,6 +55,7 @@ else
 			--exif-libdir=* )	exif_libdir="${i#--exif-libdir=}" ;;
 			--exif-includedir=* )	exif_includedir="${i#--exif-includedir=}" ;;
 			--force-qt3 )		force_qt3="true" ;;
+			--without-kde )	without_kde="true" ;;
 		esac
 	done
 
@@ -95,19 +85,8 @@ else
 		fi
 	fi
 
-	pkg-config --exists 'QtGui >= 4'
-	if [ $? -eq 0 ] && [ "$force_qt3" = "" ]
+	if [ -d "$qimage_libdir" -a -d "$qimage_includedir" ]
 	then
-		echo "Qt version 4.x detected, will compile Qt4 qimage producer"
-		qt4_found=true
-		echo "#define USE_QT4" >> config.h
-		echo "USE_QT4=1" >> config.mak
-		echo QTCXXFLAGS=$(pkg-config --cflags QtCore QtGui QtXml QtSvg ) >> config.mak
-		echo QTLIBS=$(pkg-config --libs QtCore QtGui QtXml QtSvg) >> config.mak
-		
-	elif [ -d "$qimage_libdir" -a -d "$qimage_includedir" ]
-	then
-
 		# test if we have a Qt3 or Qt4
 		if [ -f "$qimage_libdir/libQtCore.so" ] || [ -d "$qimage_libdir/QtGui.framework" ] || [ -f "$qimage_libdir/libQtCore4.a" ] && [ "$force_qt3" = "" ]
 		then
@@ -130,22 +109,22 @@ else
 			elif [ -f "$qimage_libdir/libQtCore4.a" ]
 			then
 				echo QTCXXFLAGS=-I$qimage_includedir >> config.mak
-				echo QTLIBS=-enable-auto-import -L$qimage_libdir -lQtCore4 -lQtGui4 -lQtXml4 -lQtSvg4 >> config.mak
+				echo QTLIBS=-Wl,-enable-auto-import -L$qimage_libdir -lQtCore4 -lQtGui4 -lQtXml4 -lQtSvg4 >> config.mak
 			else
 				echo QTCXXFLAGS=-I$qimage_includedir >> config.mak
 				echo QTLIBS=-L$qimage_libdir -lQtCore -lQtGui -lQtXml -lQtSvg >> config.mak
 			fi
-		else 
-		    if [ -d "$kde_includedir" ]
-		    then 
-			    echo "#define USE_KDE" >> config.h
-			    echo "USE_KDE=1" >> config.mak
+		else
+		    if [ "$without_kde" = "" ] && [ -d "$kde_includedir" ]
+		    then
+			    echo "#define USE_KDE3" >> config.h
+			    echo "USE_KDE3=1" >> config.mak
 			    echo "#define USE_QT3" >> config.h
 			    echo "USE_QT3=1" >> config.mak
 			    echo QTCXXFLAGS=-I$qimage_includedir -I$kde_includedir -DQT_THREAD_SUPPORT >> config.mak
 				echo QTLIBS=-L$qimage_libdir -L$kde_libdir -lqt-mt >> config.mak
-		    else 
-			    echo "qimage: KDE environment not found - disabling extra image formats"
+		    else
+			    echo "qimage: KDE environment not found or disabled by request - disabling extra image formats"
 			    echo "#define USE_QT3" >> config.h
 			    echo "USE_QT3=1" >> config.mak
 			    echo QTCXXFLAGS=-I$qimage_includedir -DQT_THREAD_SUPPORT>> config.mak
@@ -153,8 +132,47 @@ else
 		    fi
 		fi
 	else
-		echo "qimage: QT environment not found - disabling"
-		touch ../disable-qimage
+		pkg-config --exists 'QtGui >= 4'
+		if [ $? -eq 0 ] && [ "$force_qt3" = "" ]
+		then
+			echo "Qt version 4.x detected, will compile Qt4 qimage producer"
+			qt4_found=true
+			echo "#define USE_QT4" >> config.h
+			echo "USE_QT4=1" >> config.mak
+			echo QTCXXFLAGS=$(pkg-config --cflags QtCore QtGui QtXml QtSvg ) >> config.mak
+			echo QTLIBS=$(pkg-config --libs QtCore QtGui QtXml QtSvg) >> config.mak
+		else
+			echo "qimage: QT environment not found - disabling"
+			touch ../disable-qimage
+		fi
 	fi
 
+	if [ "$without_kde" = "" ]
+	then
+		kde4-config
+		if [ $? -eq 0 ] && [ "$qt4_found" != "" ]
+		then
+			# test if we have KDE4, required on some systems to get QImage extra formats (xcf, ...)
+			if [ "$kde_includedir" = "" ]
+			then
+				  kde_includedir=`kde4-config --install include`
+			fi
+			if [ "$kde_libdir" = "" ]
+			then
+				  kde_libdir=`kde4-config --install lib`
+			fi
+			if [ -d "$kde_includedir" ] && [ -d "$kde_libdir" ]
+			then
+				echo "KDE version 4.x detected, will enable extra image formats"
+				echo "#define USE_KDE4" >> config.h
+				echo "USE_KDE4=1" >> config.mak
+				echo KDECXXFLAGS=-I$kde_includedir >> config.mak
+				# the -L with kde4/devel is for Fedora
+				echo KDELIBS=-L$kde_libdir -L${kde_libdir}/kde4/devel -lkdecore >> config.mak
+			fi
+		fi
+	fi
+
+	[ "$gpl3" = "true" ] && echo GPL3=1 >> config.mak
+	exit 0
 fi
