- 6.18.0 src

diff --git a/mlt/src/swig/python/build b/mlt/src/swig/python/build
--- a/mlt/src/swig/python/build
+++ b/mlt/src/swig/python/build
@@ -1,6 +1,8 @@
 #!/bin/sh
 
 CXX=${CXX:-g++}
+PYTHON=${PYTHON:-python3}
+path=`which "$PYTHON" 2> /dev/null`
 
 if [ "$1" = "clean" ]
 then
@@ -8,14 +10,11 @@ then
 	exit 0
 fi
 
-path=`which python 2> /dev/null`
-
 if [ $? = 0 ]
 then
 	# Change this as needed
-	export PYTHON_INCLUDE=`python -c "import sys;print(\"{}/include/python{}.{}\".format(sys.prefix,*sys.version_info))"`
-
-	[ ! -d "$PYTHON_INCLUDE" ] && echo python development missing && exit 1
+	export PYTHON_INCLUDE="$("${PYTHON}-config" --includes)"
+	[ -z "$PYTHON_INCLUDE" ] && echo "$PYTHON" development missing && exit 1
 
 	ln -sf ../mlt.i
 
@@ -23,10 +22,10 @@ then
 	swig -c++ -I../../mlt++ -I../.. -python mlt.i || exit $?
 
 	# Compile the wrapper
-	${CXX} -fPIC -D_GNU_SOURCE ${CXXFLAGS} -c -I../.. -I$PYTHON_INCLUDE mlt_wrap.cxx || exit $?
+	${CXX} -fPIC -D_GNU_SOURCE ${CXXFLAGS} -c -I../.. $PYTHON_INCLUDE mlt_wrap.cxx || exit $?
 
 	# Create the module
-	${CXX} ${CXXFLAGS} -shared mlt_wrap.o -L../../mlt++ -lmlt++ -L../../framework -lmlt $(python-config --ldflags) -o _mlt.so || exit $?
+	${CXX} ${CXXFLAGS} -shared mlt_wrap.o -L../../mlt++ -lmlt++ -L../../framework -lmlt $("${PYTHON}-config" --ldflags) -o _mlt.so || exit $?
 else
 	echo Python not installed.
 	exit 1
